// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDKtYn6fqTtn74rP3wu6SKbldG8Egbz0qw',
    appId: '1:367988417331:web:16c6cef60cdf393609d446',
    messagingSenderId: '367988417331',
    projectId: 'todolist-flutter-88ee6',
    authDomain: 'todolist-flutter-88ee6.firebaseapp.com',
    storageBucket: 'todolist-flutter-88ee6.appspot.com',
    measurementId: 'G-Y7FF8P3200',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCJSsgwodttj_1QceV21uPm7t2NRt9WIu4',
    appId: '1:367988417331:android:f8163c6b424299b009d446',
    messagingSenderId: '367988417331',
    projectId: 'todolist-flutter-88ee6',
    storageBucket: 'todolist-flutter-88ee6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAYR7rVhgHzAW2oq0oZsRaKlB42jEaQ4BU',
    appId: '1:367988417331:ios:043743088258e22c09d446',
    messagingSenderId: '367988417331',
    projectId: 'todolist-flutter-88ee6',
    storageBucket: 'todolist-flutter-88ee6.appspot.com',
    iosBundleId: 'com.example.todoList',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAYR7rVhgHzAW2oq0oZsRaKlB42jEaQ4BU',
    appId: '1:367988417331:ios:346bbb29df8ea48f09d446',
    messagingSenderId: '367988417331',
    projectId: 'todolist-flutter-88ee6',
    storageBucket: 'todolist-flutter-88ee6.appspot.com',
    iosBundleId: 'com.example.todoList.RunnerTests',
  );
}
